# Generated by Django 3.1.2 on 2020-11-12 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20201112_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 11, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='Iran', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='Peyman', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 11, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='oop', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
